//= require 'jquery'
//= require 'underscore'
//= require 'backbone'
//
//= require 'initializer'
//= require 'colors'
//= require 'models/pixel'
//= require 'models/imageData'
//= require 'lib/imageFunctions'
//= require 'canvas'
//= require 'lineCanvas'
//= require 'canvases/characterCanvas'
//= require 'canvases/textCanvas'
//= require 'views/mainView'
//= require 'views/histogramView'
//= require 'views/waveformView'
